spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: banking-service
          uri: lb://BANKING-SERVICE
          predicates:
            - Path=/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/