spring:
  application:
    name: banking-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/