version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankingdb
      MYSQL_USER: bankinguser
      MYSQL_PASSWORD: bankingpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banking-network

volumes:
  mysql_data:

networks:
  banking-network:
    driver: bridge
